import {
  Laptop,
  Shirt,
  Droplets,
  FileText,
  Pill,
  CookingPot,
  MoreHorizontal,
  PenTool,
  Cross,
  Package,
  Camera,
  Plane,
  Map,
  Wallet,
  Umbrella,
  Glasses,
  Key,
  Book,
  Music,
  Smartphone,
  Sun,
  Snowflake,
  Coffee,
  LucideIcon,
  HelpCircle,
  Notebook,
  TriangleAlert,
} from "lucide-react";

export const iconMap: Record<string, LucideIcon> = {
  laptop: Laptop,
  shirt: Shirt,
  droplets: Droplets,
  "file-text": FileText,
  pill: Pill,
  "cooking-pot": CookingPot,
  "more-horizontal": MoreHorizontal,
  "pen-tool": PenTool,
  cross: Cross,
  package: Package,
  camera: Camera,
  plane: Plane,
  map: Map,
  wallet: Wallet,
  umbrella: Umbrella,
  glasses: Glasses,
  key: Key,
  book: Book,
  music: Music,
  smartphone: Smartphone,
  sun: Sun,
  snowflake: Snowflake,
  coffee: Coffee,
  notebook: Notebook,
  "triangle-alert": TriangleAlert,
};

export function getIcon(name: string | null | undefined): LucideIcon {
  if (!name) return HelpCircle;
  return iconMap[name] || HelpCircle;
}
